### ISSUE TITLE
红米K50最新开发版模拟失败并且闪退

### ISSUE THREAD

**Issue by whao123yahoo** [Xposed-Modules-Repo/net.ankio.bluetooth#1]
rt，机型红米K50普通版。系统版本为最新开发版。进入扫描界面以后直接按返回都会报错，而且模拟不起作用。
错误代码如下，通过AI机器人分析得出如下结论，该错误代码是由于在使用迭代器遍历ArrayList集合进行删除元素操作时，同时又在其他地方对该集合进行了修改，导致了当前集合被修改而抛出的ConcurrentModificationException异常。具体出现的位置在MainActivity.kt的第412行和第254行。解决方法是使用迭代器的remove()方法来删除元素，或者使用同步集合（例如CopyOnWriteArrayList）来避免并发修改异常。
[本消息是自动回复]
，java.lang.RuntimeException: Unable to resume activity {net.ankio.bluetooth/net.ankio.bluetooth.MainActivityLauncher}: java.util.ConcurrentModificationException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4945)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4978)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at net.ankio.bluetooth.ui.MainActivity.saveToLocal(MainActivity.kt:412)
	at net.ankio.bluetooth.ui.MainActivity$setMacBluetoothData$1$1.afterTextChanged(MainActivity.kt:254)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:11095)
	at android.widget.TextView.setText(TextView.java:6657)
	at android.widget.TextView.setText(TextView.java:6462)
	at android.widget.EditText.setText(EditText.java:124)
	at android.widget.TextView.setText(TextView.java:6414)
	at net.ankio.bluetooth.ui.MainActivity.setMacBluetoothData(MainActivity.kt:238)
	at net.ankio.bluetooth.ui.MainActivity.onResume(MainActivity.kt:152)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1564)
	at android.app.Activity.performResume(Activity.java:8674)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4934)
	... 13 more

**Comment by dreamncn** [comment]
已修复：https://github.com/dreamncn/bluetooth/commit/2341a2173c3ed9589982213859375b50464674bc
